kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: {{.Values.storage.classname }}
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_LRS
  location: {{ .Values.location }}