kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{.Values.wp.persistentvolumeclaim.name}}
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.storage.classname }}
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.wp.persistentvolumeclaim.size}}