---
kind: Service
apiVersion: v1
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wordpress-pv
  annotations:
    volume.beta.kubernetes.io/storage-class: slow
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - name: wordpress
        image: wordpress:4.6.1-apache
        ports:
          - containerPort: 80
            name: wordpress
        volumeMounts:
        - mountPath: /var/www/html
          name: wordpressvolume
        env: 
        - name: "WORDPRESS_DB_HOST"
          value: mysql
        - name: "WORDPRESS_DB_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
      volumes: 
      - name: wordpressvolume
        persistentVolumeClaim:
          claimName: wordpress-pv
