# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
location: westus
storage:
  classname: chartclass
mysql:
  image:
    repository: mysql
    tag: 5.6
  database:
    dbname: samplechart
    dbuser: mychartuser
  persistentvolumeclaim:
    name: mysql-pvc
    size: 5Gi
  service:
    name: mysqlchart
    type: LoadBalancer
    port: 3306
    targetport: 3306
wp:
  image:
    repository: wordpress
    tag: 4.6.1-apache
  service:
    name: wpchart
    port: 80
  persistentvolumeclaim:
   name: wp-pvc
   size: 8Gi
